// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetService bridges the frontend UI and the network layer.
 * Its exported methods are callable from the frontend JavaScript.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * ClearCounters resets byte/packet counters.
 * @returns {$CancellablePromise<void>}
 */
export function ClearCounters() {
    return $Call.ByID(4114328947);
}

/**
 * Connect establishes a connection based on the provided config.
 * @param {model$0.ConnectionConfig} config
 * @returns {$CancellablePromise<string>}
 */
export function Connect(config) {
    return $Call.ByID(285286569, config);
}

/**
 * Disconnect tears down the current connection.
 * @returns {$CancellablePromise<string>}
 */
export function Disconnect() {
    return $Call.ByID(742123995);
}

/**
 * DisconnectClient disconnects a specific TCP client.
 * @param {string} clientID
 * @returns {$CancellablePromise<string>}
 */
export function DisconnectClient(clientID) {
    return $Call.ByID(2780377404, clientID);
}

/**
 * GetByteCounters returns current byte statistics.
 * @returns {$CancellablePromise<model$0.ByteCounters>}
 */
export function GetByteCounters() {
    return $Call.ByID(1901275360).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetClients returns the list of connected TCP clients.
 * @returns {$CancellablePromise<model$0.ClientInfo[]>}
 */
export function GetClients() {
    return $Call.ByID(3296347873).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetLocalIP returns the device's preferred local IP address
 * by dialing a UDP connection to determine the outbound interface.
 * @returns {$CancellablePromise<string>}
 */
export function GetLocalIP() {
    return $Call.ByID(410731735);
}

/**
 * GetState returns current connection info.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetState() {
    return $Call.ByID(3891542184).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Send sends text data from the frontend.
 * @param {string} text
 * @returns {$CancellablePromise<string>}
 */
export function Send(text) {
    return $Call.ByID(3197907519, text);
}

/**
 * SendHex sends hex-encoded data (e.g., "48 65 6c 6c 6f").
 * @param {string} hexStr
 * @returns {$CancellablePromise<string>}
 */
export function SendHex(hexStr) {
    return $Call.ByID(295360312, hexStr);
}

/**
 * SendHexToClient sends hex data to a specific TCP client.
 * @param {string} clientID
 * @param {string} hexStr
 * @returns {$CancellablePromise<string>}
 */
export function SendHexToClient(clientID, hexStr) {
    return $Call.ByID(2142835418, clientID, hexStr);
}

/**
 * SendToClient sends data to a specific client (TCP server mode).
 * @param {string} clientID
 * @param {string} text
 * @returns {$CancellablePromise<string>}
 */
export function SendToClient(clientID, text) {
    return $Call.ByID(4028714489, clientID, text);
}

/**
 * SetApp sets the application reference for event emission.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3493007622, app);
}

/**
 * SetDisplayMode switches between "text" and "hex" display.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetDisplayMode(mode) {
    return $Call.ByID(2664119468, mode);
}

/**
 * SetRemoteAddr updates the remote IP and port (useful for UDP dynamic target changes).
 * @param {string} ip
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function SetRemoteAddr(ip, port) {
    return $Call.ByID(3519564118, ip, port);
}

// Private type creation functions
const $$createType0 = model$0.ByteCounters.createFrom;
const $$createType1 = model$0.ClientInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
