// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ByteCounters tracks sent/received statistics.
 */
export class ByteCounters {
    /**
     * Creates a new ByteCounters instance.
     * @param {Partial<ByteCounters>} [$$source = {}] - The source object to create the ByteCounters.
     */
    constructor($$source = {}) {
        if (!("bytesSent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesSent"] = 0;
        }
        if (!("bytesReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesReceived"] = 0;
        }
        if (!("packetsSent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["packetsSent"] = 0;
        }
        if (!("packetsReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["packetsReceived"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ByteCounters instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ByteCounters}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ByteCounters(/** @type {Partial<ByteCounters>} */($$parsedSource));
    }
}

/**
 * ClientInfo describes a connected TCP client (server mode).
 */
export class ClientInfo {
    /**
     * Creates a new ClientInfo instance.
     * @param {Partial<ClientInfo>} [$$source = {}] - The source object to create the ClientInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("remoteAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteAddr"] = "";
        }
        if (!("connectedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectedAt"] = "";
        }
        if (!("bytesSent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesSent"] = 0;
        }
        if (!("bytesReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesReceived"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClientInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientInfo(/** @type {Partial<ClientInfo>} */($$parsedSource));
    }
}

/**
 * ConnectionConfig holds all user-configured connection parameters.
 */
export class ConnectionConfig {
    /**
     * Creates a new ConnectionConfig instance.
     * @param {Partial<ConnectionConfig>} [$$source = {}] - The source object to create the ConnectionConfig.
     */
    constructor($$source = {}) {
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {Protocol}
             */
            this["protocol"] = Protocol.$zero;
        }
        if (!("localIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localIp"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("remoteIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteIp"] = "";
        }
        if (!("remotePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remotePort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionConfig(/** @type {Partial<ConnectionConfig>} */($$parsedSource));
    }
}

/**
 * Protocol is the network protocol mode.
 * @readonly
 * @enum {string}
 */
export const Protocol = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ProtoTCPClient: "tcp-client",
    ProtoTCPServer: "tcp-server",
    ProtoUDP: "udp",
};
